version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
     ports:
      - "6379:6379"
    volumes:
      - redis-data:/data   # <-- Add this line
    networks:
      - app-network

volumes:
  redis-data:               # <-- And this
  
networks:
  app-network:
