FROM python:3.9-slim
#set working directory
WORKDIR /app
#Copy dependencies
COPY requirements.txt
#Install dependencies
RUN pip install -r requirements.txt
#Copy the rest of the code
COPY . .
#Expose the flask app
EXPOSE 5000
#Start the flask app
CMD ["python", "app.py"]   
#why app.py :  
  
